- name: Test compile for Arduino
  uses: ArminJo/arduino-test-compile@v2.2.0
  with:
    # Version of arduino-cli to use when builing. Current (3/2020) one is 0.9.0.
    cli-version: 0.9.0
    # Comma sepatated list of patterns or filenames (without path) of the sketch(es) to test compile. Useful if the sketch is a *.cpp or *.c file or only one sketch in the repository should be compiled.
    sketch-names: /firmware/main.ino
    # Fully Qualified Board Name of the Arduino board. You may add a suffix behind the fqbn with "|" to specify one board for e.g. different compile options like arduino:avr:uno|trace.
    arduino-board-fqbn: # optional, default is arduino:avr:uno
    # The platform specifier, if you require a fixed version like arduino:avr@1.8.2 or do not want the specifier derived from the 2 first elements of the arduino-board-fqbn
    arduino-platform: # optional, default is 
    # The platform URL for the required board description if arduino-board-fqbn does not start with "arduino:".
    platform-url: # optional, default is 
    # Comma separated list of arduino library names required for compiling the sketches / examples for this board.
    required-libraries: # optional, default is 
    # Comma or space separated list of significant prefixes of all sketches / examples to be excluded in the build for this board.
    examples-exclude: # optional, default is 
    # Build parameter like -DDEBUG for each example specified or for all examples, if example name is "All". In json format.
For example: examples-build-properties: '{ "WhistleSwitch": "-DDEBUG -DFREQUENCY_RANGE_LOW", "SimpleFrequencyDetector": "-DINFO" }'

    examples-build-properties: # optional, default is 
    # If set to "true" she action logs verbose compile output even during successful builds
    debug: # optional, default is 
